export default function TermsPage() {
  return (
    <main className="min-h-screen bg-void text-[#F8F9FC]">
      <div className="max-w-3xl mx-auto px-6 py-20">
        <h1 className="text-4xl font-bold mb-2" style={{ fontFamily: 'var(--font-display)' }}>
          Terms of Service
        </h1>
        <p className="text-[#555] text-sm mb-10">Last updated: May 2026</p>

        <div className="space-y-8 text-[#999] leading-relaxed text-[15px]">
          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              1. Acceptance of Terms
            </h2>
            <p>By creating an account or using the Service, you confirm that you are at least 18 years old and agree to these Terms. We may update these Terms from time to time — continued use constitutes acceptance of changes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              2. Account Registration
            </h2>
            <p>You must provide a valid email address to create an account. You are responsible for maintaining the confidentiality of your account credentials. You must not share your account with others.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              3. Tiers of Service
            </h2>

            <div className="bg-card border border-border rounded-2xl p-6 space-y-4">
              <div>
                <h3 className="text-gold font-semibold mb-1">Tier 1: Free (Ad-Supported)</h3>
                <ul className="list-disc list-inside space-y-1 text-sm">
                  <li>2 video renders per day (UTC midnight reset)</li>
                  <li>3 edits per video (4 versions maximum)</li>
                  <li>Watermarked with soonsnap.richysoonak.com</li>
                  <li>Ad-supported experience</li>
                  <li>720p resolution</li>
                </ul>
              </div>
              <div>
                <h3 className="text-gold font-semibold mb-1">Tier 2: SOONAK Holder</h3>
                <ul className="list-disc list-inside space-y-1 text-sm">
                  <li>Requires holding 200+ $SOONAK tokens in a linked Solana wallet</li>
                  <li>2 video renders per day (UTC midnight reset)</li>
                  <li>5 edits per video (6 versions maximum)</li>
                  <li>No watermark, no ads</li>
                  <li>1080p resolution</li>
                  <li>Token balance is verified via read-only Solana RPC — no signature or transaction required</li>
                </ul>
              </div>
              <div>
                <h3 className="text-teal font-semibold mb-1">Tier 3: Pro (Credit-Based)</h3>
                <ul className="list-disc list-inside space-y-1 text-sm">
                  <li>No daily limits — purchase credits to render</li>
                  <li>Unlimited edits per video</li>
                  <li>No watermark, no ads</li>
                  <li>1080p resolution</li>
                  <li>Credits are non-refundable and never expire</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              4. Acceptable Use
            </h2>
            <p>You agree NOT to:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Use the Service to generate videos featuring illegal, harmful, threatening, abusive, or defamatory content</li>
              <li>Submit URLs that contain malware, phishing, or illegal material</li>
              <li>Attempt to bypass watermarks, ads, or tier restrictions</li>
              <li>Use automated tools to abuse the Service beyond provided API limits</li>
              <li>Reverse-engineer, decompile, or modify the Service</li>
              <li>Resell or redistribute videos generated on a free tier without the watermark</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              5. Intellectual Property
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li><span className="text-[#F8F9FC] font-medium">Your content:</span> You retain ownership of any website content you submit for video generation. By submitting a URL, you confirm you have the right to use any content, logos, or trademarks featured on that website.</li>
              <li><span className="text-[#F8F9FC] font-medium">Generated videos:</span> You own the videos generated by the Service. Tier 1 videos include a watermark — you may not remove it. Tier 2 and 3 videos are provided without watermark for your unrestricted use.</li>
              <li><span className="text-[#F8F9FC] font-medium">SoonSnap branding:</span> The SoonSnap name, logo, and brand materials are the property of SOONAK. You may not use them without written permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              6. SOONAK Token Integration
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li>Tier 2 access is contingent on maintaining a balance of 200+ $SOONAK tokens in your linked Solana wallet.</li>
              <li>We verify token balances via read-only RPC calls — we never request wallet signatures, spending authority, or on-chain transactions.</li>
              <li>If your balance drops below 200 tokens, your account will be downgraded to Tier 1 at the next verification cycle.</li>
              <li>We are not responsible for token price fluctuations, network issues, or wallet compatibility problems.</li>
              <li>$SOONAK is a cryptocurrency and carries inherent risk. We do not guarantee its value, liquidity, or future performance.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              7. Payments (Tier 3)
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li>Credit purchases are processed via Stripe.</li>
              <li>All prices are in USD and include applicable taxes.</li>
              <li>Credits are non-refundable once purchased.</li>
              <li>Credits never expire.</li>
              <li>We reserve the right to change credit pricing with 30 days&apos; notice.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              8. Disclaimer of Warranties
            </h2>
            <p>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied. We do not guarantee:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>The Service will be uninterrupted, error-free, or secure</li>
              <li>Video generation results will meet your expectations</li>
              <li>Any specific quality, accuracy, or timeliness of results</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              9. Limitation of Liability
            </h2>
            <p>To the maximum extent permitted by law, SOONAK shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for credits in the 12 months preceding the claim, or $100, whichever is greater.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              10. Termination
            </h2>
            <p>We may suspend or terminate your account for violation of these Terms. You may delete your account at any time by contacting us. Upon termination, any purchased credits remain non-refundable.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              11. Governing Law
            </h2>
            <p>These Terms are governed by the laws of England and Wales. Any disputes shall be resolved in the courts of England.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#F8F9FC] mb-3" style={{ fontFamily: 'var(--font-display)' }}>
              12. Contact
            </h2>
            <p>For questions about these Terms, contact: <span className="text-gold">soonsnap@richysoonak.com</span></p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border">
          <a href="/soonsnap/" className="text-teal hover:text-gold transition-colors text-sm">← Back to SoonSnap</a>
        </div>
      </div>
    </main>
  );
}
